apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: helm-app  
   #namespace: argocd
spec: 
  destination: 
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm-guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
     releaseName: my-release
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true

    
