apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: webapp
  spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm/webapp
    repoURL: "https://github.com/silandrew/argocd-course-webapp-config.git"
    targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      allowEmpty: true
      selfHeal: true
      

    
